CREATE TABLE [Identity].[Role]
(
	[Id] NVARCHAR(255) NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
    [NormalizedName] NVARCHAR(255) NOT NULL,
    [ConcurrencyStamp] NVARCHAR(255) NOT NULL,

	CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED
	(
		[Id]
	)
)
GO